# Generated by Django 4.0.4 on 2023-02-02 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicaciones',
            name='banner',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
