# Generated by Django 4.0.4 on 2023-02-02 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integra', '0002_alter_publicaciones_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicaciones',
            name='experiencia',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='publicaciones',
            name='fecha_limite',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='publicaciones',
            name='salario',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='publicaciones',
            name='vacantes',
            field=models.IntegerField(blank=True),
        ),
    ]
