# Generated by Django 4.0.4 on 2023-02-02 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integra', '0003_alter_publicaciones_experiencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicaciones',
            name='experiencia',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publicaciones',
            name='salario',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publicaciones',
            name='vacantes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
