# Generated by Django 4.0.4 on 2023-02-05 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integra', '0004_alter_publicaciones_experiencia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.AddField(
            model_name='publicaciones',
            name='dep',
            field=models.ManyToManyField(to='integra.departamento'),
        ),
    ]
